'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)];
const source=scripts.at(-1)[1];
const begin=source.indexOf('function dayNow()');
const end=source.indexOf('function counts(){',begin);
assert(begin>=0&&end>begin,'calendar functions missing');
const ctx={Date,console};
vm.runInNewContext(source.slice(begin,end)+'\nthis.deadline=startDeadlineLabel;this.nextDate=quickDateOffset;',ctx,{timeout:10000});
const make=(type,date,end_date)=>({type,date,job:{end_date}});
assert.equal(ctx.deadline(make('start','2026-10-02','2026-10-14'),false),'마감 D-12');
assert.equal(ctx.deadline(make('start','2026-10-02','2026-10-14'),true),'D-12');
assert.equal(ctx.deadline(make('start','2026-10-14','2026-10-14'),false),'마감 D-Day');
assert.equal(ctx.deadline(make('start','2026-10-02',''),false),'');
assert.equal(ctx.deadline(make('close','2026-10-14','2026-10-14'),false),'');
assert.equal(ctx.deadline(make('start','2026-10-15','2026-10-14'),false),'마감일 확인');
assert.equal(ctx.nextDate('2026-10-31',1),'2026-11-01');
assert.equal(ctx.nextDate('2026-11-01',-1),'2026-10-31');
assert.equal(ctx.nextDate('2027-01-01',-1),'2026-12-31');
assert(html.includes("'touchstart'")&&html.includes("'touchend'"),'touch swipe listeners missing');
assert(html.includes('Math.abs(dx)>55'),'horizontal swipe threshold missing');
assert(html.includes('Math.abs(dx)>Math.abs(dy)*1.35'),'vertical scroll protection missing');
assert(!html.includes('document.body.style.overflow=\\'hidden\\''),'calendar should not be scroll-locked');
assert(html.includes('role="region" aria-labelledby="quickDateTitle"'),'nonmodal dock missing');
assert(!html.includes('<div class="quick-backdrop" data-quick-close>'),'obscuring backdrop remains');
console.log('PASS D-day, dates across months, nonmodal dock, swipe/vertical-scroll protection');
