'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)];
const source=scripts.at(-1)[1];
const begin=source.indexOf('function dayNow()');
const end=source.indexOf('function counts(){',begin);
assert(begin>=0&&end>begin,'calendar functions missing');
const ctx={Date,console};
const extract=(start,end)=>{const i=source.indexOf(start);const j=source.indexOf(end,i+start.length);assert(i>=0&&j>i,`missing section ${start}`);return source.slice(i,j)};
const isolated=[extract('function dateOnly(','function uniqueDatesMatch('),extract('function dayNow()','function counts(){'),extract('function startDeadlineLabel(','function renderCalendar(){'),extract('function quickDateOffset(','function showQuickDate(')].join('\n');
const testGlobals=`const EVENT_KEYS={start:'start_date',close:'end_date',result:'result_date',test:'test_date'};const EVENT_NAMES={start:'시작',close:'마감',result:'발표',test:'인적성'};const settings={events:['start','close','result','test']};const normCompany=s=>s.toLowerCase();const isApplied=()=>false;\n`;
vm.runInNewContext(testGlobals+isolated+'\nthis.deadline=startDeadlineLabel;this.nextDate=quickDateOffset;this.makeEvents=eventsFor;this.grouped=groupedCalendarPreview;',ctx,{timeout:10000});
const make=(type,date,end_date)=>({type,date,job:{end_date}});
assert.equal(ctx.deadline(make('start','2026-10-02','2026-10-14'),false),'마감 D-12');
assert.equal(ctx.deadline(make('start','2026-10-02','2026-10-14'),true),'D-12');
assert.equal(ctx.deadline(make('start','2026-10-14','2026-10-14'),false),'마감 D-Day');
assert.equal(ctx.deadline(make('start','2026-10-02',''),false),'');
assert.equal(ctx.deadline(make('close','2026-10-14','2026-10-14'),false),'');
assert.equal(ctx.deadline(make('start','2026-10-15','2026-10-14'),false),'마감일 확인');
assert.equal(ctx.nextDate('2026-10-31',1),'2026-11-01');
assert.equal(ctx.nextDate('2026-11-01',-1),'2026-10-31');
assert.equal(ctx.nextDate('2027-01-01',-1),'2026-12-31');
const duplicates=ctx.makeEvents([{id:'one',start_date:'2026-10-21',end_date:'2026-10-21',result_date:'',test_date:''}]);
assert.equal(duplicates.length,1,'same vacancy should show once on the same calendar day');
assert.equal(duplicates[0].label,'시작·마감');
assert.equal(duplicates[0].type,'close');
const jobs=[{id:'x1',company:'삼천리',start_date:'2026-10-08',end_date:'2026-10-21',result_date:'',test_date:''},{id:'x2',company:'삼천리',start_date:'2026-10-08',end_date:'2026-10-21',result_date:'',test_date:''}];
const grouped=ctx.grouped(ctx.makeEvents(jobs).filter(x=>x.type==='close'));
assert.equal(grouped.length,1,'same-company same-date closing chips should combine in narrow calendar');
assert.equal(grouped[0].count,2,'separate role count must remain available');
const distinctDeadlines=ctx.grouped(ctx.makeEvents([{...jobs[0]},{...jobs[1],end_date:'2026-10-22'}]).filter(x=>x.type==='start'));
assert.equal(distinctDeadlines.length,2,'start events with different deadlines must stay separate');
assert(html.includes("'touchstart'")&&html.includes("'touchend'"),'touch swipe listeners missing');
assert(html.includes('Math.abs(dx)>55'),'horizontal swipe threshold missing');
assert(html.includes('Math.abs(dx)>Math.abs(dy)*1.35'),'vertical scroll protection missing');
assert(!html.includes("document.body.style.overflow='hidden'"),'calendar should not be scroll-locked');
assert(html.includes('role="region" aria-labelledby="quickDateTitle"'),'nonmodal dock missing');
assert(!html.includes('<div class="quick-backdrop" data-quick-close>'),'obscuring backdrop remains');
console.log('PASS D-day, dates across months, nonmodal dock, swipe/vertical-scroll protection');
